version: "3.1"

services:
  db:
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web
      MYSQL_USER: userdb
      MYSQL_PASSWORD: rahasia
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
